version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www
    networks:
      - laravel

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: example
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  # Composer Service
  composer:
    image: composer
    container_name: laravel_composer
    volumes:
      - .:/var/www
    networks:
      - laravel

volumes:
  mysql_data:
    driver: local

networks:
  laravel:
    driver: bridge
